### ISSUE TITLE
Unsupported important APIs

### ISSUE THREAD

**Issue by mytototo** [APIs-guru/openapi-directory#103]
Hi!

Do you have any plan to add AWS, Stripe, Facebook, Twitter or some other important APIs?

Thanks.

**Comment by IvanGoncharov** [comment]
@mytototo Yes definitely. But in order to add API into the collection, I need to have a link to API specification in one of the popular formats (RAML, OpenAPI/Swagger, WADL, ...). If you can send me such URLs to API that you mentioned I will add it to the collection.

The purpose of this project is to aggregate existing API specs. So, if you want to help you can write scraper which converts official HTML docs into OpenAPI spec.

**Comment by IvanGoncharov** [comment]
@mytototo We plan to add AWS in future, see #104

**Comment by MikeRalphson** [comment]
There is a Facebook definition in WADL format at http://api.apigee.com/v1/consoles/facebook/apidescription?format=wadl

I don't know how up-to-date it is.

**Comment by IvanGoncharov** [comment]
@MikeRalphson When I fist discovered Apigee consoles I was so excited that wrote special scraper for them: https://github.com/APIs-guru/apigee-scraper
But then I started to check specs found that most of them are unofficial specs with a lot of mistakes. Moreover almost all them is outdated you can check `lastUpdatedAt` tag in [consoles.json](http://api.apigee.com/v1/consoles.json).
I see that only `Factual`, `Fitbit` and `OneNote` were updated in 2016.
The majority of other including Facebook were written in 2012-2013.

**Comment by MikeRalphson** [comment]
@mytototo There is a read-only GraphQL API for Twitter (and HackerNews, Reddit, GitHub and Giphy) at [GraphQLHub](https://graphqlhub.com).

Although it is not a REST API, an [OpenApi specification](https://mermade.github.io/swagger/index.html?url=https://raw.githubusercontent.com/Mermade/openapi_specifications/master/GraphQLHub/swagger.json) is still useful in documenting the endpoints and outer models.

**Comment by MikeRalphson** [comment]
Added to wiki:FAQ

**Comment by MikeRalphson** [comment]
Stripe API added today.
