### ISSUE TITLE
Add "RandomGeneratedUser" API

### ISSUE THREAD

**Issue by McHenro** [APIs-guru/openapi-directory#1114]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://randomuser.me/api/
**Name**: RandomGeneratedUser
**Category**: developer_tools
**Logo**:

**Comment by MikeRalphson** [comment]
Many thanks for the contribution. Please could you provide a link to the actual *machine-readable* API definition, rather than the API endpoint itself, in either OpenAPI or one of the other supported formats (RAML, API Blueprint, Postman etc)? Without this unfortunately we cannot add the API to the directory.
