### ISSUE TITLE
Add "IP To Maps" API

### ISSUE THREAD

**Issue by alsemany** [APIs-guru/openapi-directory#112]
**Format**: I/O Docs
**Official**: YES
**Url**: https://www.iptomaps.com/api
**Name**: IP To Maps

**Comment by IvanGoncharov** [comment]
@alsemany Thank you for your submission and sorry for long delay.

> Url: https://www.iptomaps.com/api

I can't see any API spec on this page.
Can you please provide URL to you I/O Docs spec?
Without it I can't add your API into collection.

**Comment by alsemany** [comment]
Thank you, I'm just confused about the type of the API 
the url provided is already the documentation of our simple IP information API 


>  FREE API for Webmasters
> we present a free, simple and fast API for all IPs available to information without any fees. 
> Simply: get the data from 
> https://www.iptomaps.com/api/ip/ { IPV4 or IPV6 } 
> for example: https://www.iptomaps.com/api/ip/8.8.8.8 
> or 
> https://www.iptomaps.com/api/ip/2001:4860:4860::8888 

 I'm just don't understand what you meant 
Thank you anyway

**Comment by IvanGoncharov** [comment]
@alsemany This project different from other catalogs(for e.g. ProgrammableWeb) because it contains **machine-readable** documentation of APIs. Currently, you provide only human-readable docs so I can't add your API. However, you can describe your API in one of the popular formats, like OpenAPI/Swagger, RAML, etc.
Here is link to tutorial which will help you to describe your API in OpenAPI format: https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-1-introduction/

Please feel free to open reopen this issue when you will have a spec in OpenAPI or any other popular format.
