### ISSUE TITLE
Add "Neutrino API" API

### ISSUE THREAD

**Issue by NeutrinoAPI** [APIs-guru/openapi-directory#184]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://www.neutrinoapi.com/api/swagger.json
**Name**: Neutrino API
**Valid**: Yes
**Categories**: email,messaging,telecom,location,text
**Logo**: 
![image](https://cloud.githubusercontent.com/assets/21603/24491811/f0c8cf12-1520-11e7-9d5b-d32360ebfd4a.png)

**Comment by MikeRalphson** [comment]
@NeutrinoAPI has your definition originally been converted from another format?

I only ask because of the license URL:

````json
    "license": {
      "name": "MIT",
      "url": "http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT"
    }
````

I've seen this with APIMatic's API converter and reported the issue to them.

It may be better to link to an authorative copy of the [MIT license](https://opensource.org/licenses/MIT), in case grunt change their license.

**Comment by NeutrinoAPI** [comment]
Hey @MikeRalphson 
Thanks for pointing this out, we did indeed use the APIMatic app to generate this!
I have just updated our spec with our own license URL now.. I will also raise a ticket with APIMatic too so they can fix it upstream..
Cheers!

**Comment by MikeRalphson** [comment]
API added, many thanks for the submission.
