### ISSUE TITLE
Add "ゲーム情報サイト ごちゃまぜフィード" API

### ISSUE THREAD

**Issue by keigohtr** [APIs-guru/openapi-directory#202]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://api.apitore.com/json/33
**Name**: ゲーム情報サイト ごちゃまぜフィード

**Comment by keigohtr** [comment]
@MikeRalphson I fixed it. Please check my APIs again. Thank you :)

**Comment by MikeRalphson** [comment]
Looking at this API, when I make a test call against the host: `http://api.apitore.com`, I get a 302 Moved Permanently redirect to `https://api.apitore.com`. 

This may be due to a bug in Swagger-UI, but it might be worth adding a 

````json
"schemes": [
    "https"
]
````

property to the definitions to make the protocol explicit?

The next thing I noticed is your `access_token` parameter. I think this should be a `securityDefinition` as follows:

````json
"securityDefinitions": {
    "access_token": {
       "type": "apiKey",
       "in": "query",
       "name": "access_token" 
    }
},
"security": [
    {
        "access_token": []
    }
]
````

That way you will not need to define it as a parameter on every operation, and tools such as Swagger-UI will know that it is an authorization mechanism.
