### ISSUE TITLE
Yelp API - Fusion is not in the list?

### ISSUE THREAD

**Issue by pkshreeman** [APIs-guru/openapi-directory#227]
Greetings! I tried to find Yelp API  and could not.  Do you need help integrating this info?  I have used Yelp API so I may be able to contribute?

**Comment by MikeRalphson** [comment]
Hi @pkshreeman - to add an API to the collection we need a machine-readable definition of the API, e.g. Swagger / OpenAPI.

I've done a little googling and have not been able to find more than this issue https://github.com/Yelp/yelp-fusion/issues/80 - do you know if that's the current situation?

There is a Postman collection [here](https://www.getpostman.com/run-collection/a54dde1fd81323f2203e) which could be converted using Apimatic's [API Transformer](https://apimatic.io/transformer), but the quality depends on the Postman data and can sometimes need to be hand edited (e.g. to add security definitions).

We'd certainly appreciate you working on this if you have time (and no official Yelp Swagger definition is forthcoming).

**Comment by pkshreeman** [comment]
@MikeRalphson 
I have created PR with this, although I am not sure if I have done it right since I see that it is in YAML format, not JSON, and I have no idea what patch.yaml is for.

**Comment by MikeRalphson** [comment]
@pkshreeman many thanks for the PR. What we need foremost to add an API and keep it updated, is a URL from which to pull it. You could create a github project to host it, or if you don't want to be the sole maintainer you could create a PR in [this repository](https://github.com/APIs-guru/unofficial_openapi_specs). There it doesn't matter about json/yaml (as it will be converted), - APIs.guru itself is currently yaml only.

patch.yaml is used to add APIs.guru-specific vendor extensions to the definition, such as categories etc and is optional, so you don't need to worry about that.

I've checked the definition and it is valid, which is a great start. There is one issue, caused by a bug in ApiMatic's API Transformer, the license URL is set to http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT - could you change this to an authorative source for the MIT license such as https://opensource.org/licenses/MIT ?

**Comment by pkshreeman** [comment]
Ok. I closed the PR, and created the new one: https://github.com/APIs-guru/unofficial_openapi_specs/pull/16

So, the official openAPI is directly contributed by the vendors themselves, and if they are not forthcoming, we create an unofficial version in that repository where I just created the PR?

Will these appear in APIs-Guru?

Is there anything else I need to do? 

Thank you again @MikeRalphson !

**Comment by MikeRalphson** [comment]
> So, the official openAPI is directly contributed by the vendors themselves, and if they are not forthcoming, we create an unofficial version in that repository where I just created the PR?

Yes, that's basically it - though often we have to go and find the official definitions rather than have them submitted.

I've reformatted the yelp API into Yaml and made a few small edits (missing description, add {id} parameter). I had to guess at the oAuth flow type. 

Could you maybe test the API definition, to see if everything is correct? Then we can pull it into the main APIs.guru repository.

https://raw.githubusercontent.com/APIs-guru/unofficial_openapi_specs/master/yelp.com/v3/swagger.yaml

**Comment by pkshreeman** [comment]
@MikeRalphson 
I appreciate your helping me to understand this process.  I am learning a lot.  I have taken the time to analyze this, and there are several questions.  I am now able to understand better what API Transformer did, and that Postman rereads the JSON from that differently than it does straight from Yelp (took me a while to realize that and quite amount of testing).  

Why was the section on /oauth2/token taken out?  We have to use this to obtain the access_tokens to use for the rest of the API's.  It is a POST method with the body of client id and secret with grant_type of client_credentials.  

This current setup does work if you are familiar with Yelp's requirements and do some adjustments to the configuration (adding bearer {access_token} to authorization, and queries and get your own access_token somewhere else. The API Transformer added two things to every header: Content-Type and Accept which is not required.  

How does this whole thing work?  Make README.md explaining how this works?  What's the goal here?  

Thanks again!

**Comment by MikeRalphson** [comment]
> Why was the section on /oauth2/token taken out? We have to use this to obtain the access_tokens to use for the rest of the API's. It is a POST method with the body of client id and secret with grant_type of client_credentials.

Because Swagger / OpenAPI has a standard way of defining oAuth2 credential negotiation, and that's what the /oauth2/token url is for - you'll see it has become the `tokenUrl` under the `securityDefinitions`.

If you test the API definition in something like Swagger-UI and hit 'Authorise', you should be prompted for your client secret etc.

Once authenticated, the `Authorization: bearer` header is automatically added to requests.

Once this is working, we can remove the `Authorization` header parameters as they are not required.

The `Accept` and `Content-Type` headers are driven by the `produces` and `consumes` content-types in the Swagger definition. Is `application/json` correct for what this API expects and responds with?

The goal is that any Swagger-aware client will know how to do the oAuth2 negotiation and add the appropriate headers.

I think this situation (no official Swagger definition, only a Postman collection) is quite unusual, so there is no existing README covering it, but we can certainly sumarise this issue on the Wiki once we get everything working.

One question I did not find an answer to, is if there are any specific oAuth2 'scopes' which are required by Yelp's authorization?

**Comment by pkshreeman** [comment]
OK. I am a bit lost so it will take me some time to get used to this.  I have never heard of swagger until just recently with this project.  I'm rookie...obviously.  Now, I am trying to figure out how to use Swagger UI... 

Yelp requests that you cache access_token for 180 days, and not use the OAuth2 negotiation until then.   So for most of API calls, you will not be using OAuth API, but just access_token header with authorization: bearer {{token}} setup for *all* API calls. 


Hopefully these will help...

<https://www.yelp.com/developers/documentation/v3/get_started>

### Authentication
The Fusion API uses OAuth 2.0 to authenticate all endpoints. Once you've registered for the API, you should use your client_id and client_secret to request an access token from the token endpoint. With that, you'll be able to get access to the API. For detailed instructions, refer to our authentication guide.

-----

### Authentication

Yelp Fusion API uses OAuth2 for authentication. Currently, only client credentials authorization grant flow is supported. To authenticate the call to an endpoint, there are 3 steps:

Create an app to obtain your client id and secret.
Get an access token using your client id and secret.
Authenticate API calls with the access token.
Create an app on Yelp's Developers site
In order to set up your access to Yelp Fusion API, you need to create an app with Yelp. This app represents the application you'll build using our API and includes the credentials you'll need to gain access. Here are the steps for creating an app:

### Go to Create App
In the create new app form, enter information about your app, then agree to Yelp API Terms of Use and Display Requirements. Then click the Submit button.
Now you should get the client id and secret, which will be used in the next step to get an access token.
Please keep the client id and secret to yourself since they are credentials for your call to Yelp's API.
### Get an access token
To get an access token, make a POST call to the following endpoint using the client id and secret obtained from the former step. Then get the access token from the response body.

### URL
<https://api.yelp.com/oauth2/token>
Please cache your access token so you get faster access to our data by eliminating an extra request for each API call. **Tokens are valid for 180 days from their initial creation.**
Parameters
These parameters should be sent in application/x-www-form-urlencoded format in the POST call.

Name	Path	Description
grant_type	string	The OAuth2 grant type to use. Right now, only client_credentials is supported.
client_id	string	The client id for you app with Yelp.
client_secret	string	The client secret for you app with Yelp.
Response body
{
  "access_token": "ACCESS_TOKEN",
  "token_type": "bearer",
  "expires_in": 15552000
}
Name	Path	Description
access_token	string	The access token which you'll use to access Yelp Fusion API endpoints.
token_type	string	The access token type. Always returns Bearer.
expires_in	int	Represents the number of seconds after which this access token will expire. Right now it's always 15552000, which is 180 days.
Authenticate API calls with the access token
To authenticate API calls with the access token, set the Authorization HTTP header value as Bearer ACCESS_TOKEN.

**Comment by pkshreeman** [comment]
Yelp has updated their API, so this is no longer relevant.
