### ISSUE TITLE
Add "Linode" API

### ISSUE THREAD

**Issue by MikeRalphson** [APIs-guru/openapi-directory#498]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://developers.linode.com/api/v4/openapi.yaml
**Name**: Linode
**Valid**: Almost! (Scopes and typo in secScheme name)
**Logo**: Included
**Category**: cloud

**Comment by displague** [comment]
@MikeRalphson If you want to link a diff here, or spin up a stub repo with the original and recommended changes as subsequent commits, I'll make sure the team sees it.

**Comment by displague** [comment]
I would refer you to https://github.com/linode/linode-api-docs/tree/develop/src/data but that repo has gone stale as we've changed our tooling around.

The authoritative spec is the one you linked to above which, today, is only available as that public artifact.

**Comment by MikeRalphson** [comment]
Thanks @displague ! The diff is [here](https://github.com/MikeRalphson/linode-openapi/commit/2ec4875e14db55297a4233bcb84700f3131967af) - there's just one of the `scope` changes I'm not 100% confident about.

**Comment by MikeRalphson** [comment]
`x-logo` property should be an absolute URL to allow spec. relocatability.

**Comment by displague** [comment]
Your previous recommendations were merged, @MikeRalphson 

The URL used in `x-logo` is used in the generation of staging and other environments for the docs sites.  If it was absolute then those sites couldn't represent logo changes in those environments.  

Is this a spec violation concern, or simply a matter of external tools that may want to render this spec will not have a context for the base URL of the logo? (especially if the spec is an uploaded file instead of supplied as a URL to the spec)

**Comment by MikeRalphson** [comment]
Hi @displague as this is a specification extension, it can't be a spec violation, but ReDoc (from one of the originators of the `x-logo` extension) does [recommend an absolute url](https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md#logo-object).

It was more a note for me to extend our scripts to update a relative `x-logo` url by resolving it with the spec. source url, no action required on your part.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution!
