### ISSUE TITLE
Ambiguous preferred version for azure servicefabric

### ISSUE THREAD

**Issue by pimterry** [APIs-guru/openapi-directory#541]
Throughout this directory, anywhere where there's more than one version of the same API every version has an `x-preferred` field, with all but one version set to `false`, and the one preferred version set to `true`.

That's true for everything except [Azure ServiceFabric](https://github.com/APIs-guru/openapi-directory/tree/master/APIs/azure.com/servicefabric), where [2017-07-01](https://github.com/APIs-guru/openapi-directory/blob/master/APIs/azure.com/servicefabric/2017-07-01-preview/swagger.yaml) is marked with `x-preferred: true`, [5.6](https://github.com/APIs-guru/openapi-directory/blob/master/APIs/azure.com/servicefabric/5.6/swagger.yaml) doesn't have the field at all, and all the others have `x-preferred: false`.

Is there a good reason for that? Looks to me like the field has been missed for that 5.6 spec, and should be `false` there too. That would make it easier to quickly find the preferred version.

My automation is running against the entirety of the rest of the repo, and I'm pretty sure this is the only case like this.

---

As an aside, I've had a quick look at PRing a fix for this myself, but I can't seem to work it out. The `fixup` command generates a fixup.yaml & jpdiff.yaml that looks ok, but even with `update` it never seems to actually update the spec itself. I'd love a pointer on what commands exactly I should run to solve this, so I can help out with more fixes in future.

**Comment by MikeRalphson** [comment]
There's no **good** reason for it, it's possible the code to set the `x-preferred: false` is bailing because one version looks like a date and one looks like a version number.

From memory, `fixup.yaml` (and the long-proposed replacement `jpdiff.yaml`) don't affect the `x-preferred` flag which is simply round-tripped between `swagger.yaml` / `openapi.yaml` files. I should probably update `CONTRIBUTING.md` to this affect.

I'll try and patch Azure ServiceFabric and see if it stays patched. Thanks for bringing this up.

**Comment by MikeRalphson** [comment]
Seems to have survived the update process. As it looks to have been a one-off, will leave it with the manual fix for now. Thanks for pointing it out.
