### ISSUE TITLE
Add "Free Short URL Redirects" API

### ISSUE THREAD

**Issue by saippuakauppias** [APIs-guru/openapi-directory#561]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://tinyuid.com/tinyuid-swagger.yaml
**Name**: Free Short URL Redirects

**Comment by MikeRalphson** [comment]
Your swagger document `responses` and `definitions` sections appear to contain details copy and pasted from the OpenAPI-Directory's own API definition. This doesn't look right for a URL shortener.

Can you complete your definition with the responses actually returned by your API, otherwise this definition is of limited use to your users.

**Comment by saippuakauppias** [comment]
@MikeRalphson, I'm sorry!
Swagger document now fixed.
