### ISSUE TITLE
Question: multiple concurrent versions from a single provider

### ISSUE THREAD

**Issue by andypiper** [APIs-guru/openapi-directory#686]
Asking as a question rather than submitting a new spec directly.

Currently the Twitter Developer Labs specification exists in two versions, with independent internal revisions/minor versions, at two different URIs
(https://api.twitter.com/labs/1/openapi.json and /2/openapi.json, respectively). Is this expected / can the OpenAPI directory handle this and should they be submitted separately? When one version retires, will this be automatically detected when the server is rechecked in the future?

**Comment by MikeRalphson** [comment]
Thanks for the heads-up! I've added the `v2` API source, which we can support because the source URLs differ (of course) and you seem to be using different version number ranges for what we call the same 'service' (labs).

Detecting retired APIs is difficult, it's basically the same from our point of view if someone moves the URL and forgets to set up a redirect, which happens quite often. So we rely on people to tell us if an API is completely retired.

**Comment by andypiper** [comment]
Perfect, thanks for the info, Mike! Yes, after I posted this I tested it with the collection.js script and realised it would pull it in, I guess you just would have added it under labs. After "graduation" these URLs may change and new "labs" versions may come along, but as a fan and dedicated user, I'll try to let you know as things update.

**Comment by MikeRalphson** [comment]
That would be great, thanks.
