### ISSUE TITLE
Metadata about each API

### ISSUE THREAD

**Issue by wilsonmar** [APIs-guru/openapi-directory#75]
One of the reasons Wikipedia is so useful is that it maintains additional information about its subjects that the subjects themselves may not reveal , such as history of versions, even controversy.

It would be useful to have metadata on the URL which presents the swagger info, and the tool used to generate the website (mulesoft, apigee, mashery, Azure, etc.).

Keeping this latter data on vendor used can be useful as the basis for statistics on how many sites use each vendor.

**Comment by MikeRalphson** [comment]
@wilsonmar Belated thanks for your suggestion. APIs.guru tracks the source of each definition within the `x-origin` specification extension. Obviously the git repository gives us a history of versions since the API was added and we have ideas for further metadata in the future.

Any further feedback gratefully received.
