### ISSUE TITLE
Add "spoonacular Food, Recipe, Nutrition, and Restaurant API" API

### ISSUE THREAD

**Issue by ddsky** [APIs-guru/openapi-directory#769]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://spoonacular.com/application/frontend/downloads/spoonacular-openapi-3.json
**Name**: spoonacular Food, Recipe, Nutrition, and Restaurant API

**Comment by MikeRalphson** [comment]
Thanks for the submission. The API definition contains a number of validation issues. Some can be seen here: https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fspoonacular.com%2Fapplication%2Ffrontend%2Fdownloads%2Fspoonacular-openapi-3.json

Also, there are a number of

```yaml
required: []
```

In schema objects which need to be removed. The reference to the `apiKeyScheme` needs changing from `api_key` to the component name, and there is an `array` with `properties` instead of an `items` key.

I've pasted a version which passes validation into a gist [here](https://gist.github.com/MikeRalphson/122b301f66b092e1951518034d955bfb) so you can see the differences.

**Comment by ddsky** [comment]
Thanks @MikeRalphson . I have made the changes and removed all errors. There are just some warnings which are due to the "#" in the URL but I don't think this is a problem as its just a warning.

**Comment by MikeRalphson** [comment]
API added, many thanks for the contribution! Will be live on the web when the CI job finishes. Great to have you in the directory.
