### ISSUE TITLE
Add "Cnab Online" API

### ISSUE THREAD

**Issue by andersondanilo** [APIs-guru/openapi-directory#89]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: http://cnab-online.github.io/api-reference/api-reference-v1.json
**Name**: Cnab Online
**Category**: financial
**Description/natural language**: pt

**Comment by IvanGoncharov** [comment]
@andersondanilo :+1: 
Is it in Spanish?

Can you please post a link to your logo?
Any link will work, for example, you can host it in the same Github repo.

**Comment by sanchojaf** [comment]
Hi, It's not Spanish, I think is Portuguese.

**Comment by MikeRalphson** [comment]
@andersondanilo do you have a logo, other than the banner image?

**Comment by andersondanilo** [comment]
Yes Mike, http://cnab-online.github.io/img/logo.png

**Comment by MikeRalphson** [comment]
Hi @andersondanilo just one validation error in this definition

> {
  "name": "SyntaxError",
  "message": "Validation failed. /paths/file/post has a file parameter, so it must consume multipart/form-data or application/x-www-form-urlencoded"
}

If you are responsible for the definition or can contact someone who can make a change, all that needs adding is a `consumes` array with either `multipart/form-data` or `application/x-www-form-urlencoded` as appropriate. Otherwise we can patch it up here.

**Comment by andersondanilo** [comment]
Hi Mike, fixed!

**Comment by MikeRalphson** [comment]
API added, many thanks for your submission and patience.
